# Generated by Django 3.2 on 2021-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myuser_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycreditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_owner', models.CharField(max_length=30)),
                ('card_number', models.IntegerField()),
                ('expiration_date', models.DateField(max_length=10)),
                ('cvv_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='myhelp',
            name='user_email',
            field=models.EmailField(default='urvashi@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myreview',
            name='user_email',
            field=models.EmailField(default='urvashi@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
