# Generated by Django 3.2 on 2021-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mydoctors_specialition'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydoctors',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
