# Generated by Django 3.2 on 2021-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydoctors',
            name='specialition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
