# Generated by Django 3.2 on 2021-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210513_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydoctors',
            name='experience',
            field=models.CharField(default='twoyears', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mydoctors',
            name='qualification',
            field=models.CharField(default='mbbs', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mybookappointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
