# Generated by Django 3.2 on 2021-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mybookappointment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhospital',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myhospital',
            name='state',
        ),
        migrations.AlterField(
            model_name='myhospital',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
