# Generated by Django 3.2 on 2021-05-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_myhospital_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myngos',
            name='account_no',
        ),
    ]
