# Generated by Django 3.2.3 on 2021-05-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_myngos_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myngos',
            name='image',
        ),
        migrations.AddField(
            model_name='myngos',
            name='mobile',
            field=models.CharField(default='9876543234', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myngos',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
