# Generated by Django 3.2.3 on 2021-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210521_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='myngos',
            name='opening_hours',
            field=models.CharField(default='24*7', max_length=10),
            preserve_default=False,
        ),
    ]
