# Generated by Django 3.2.3 on 2021-05-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_mylaws_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='symtoms',
            name='symtom_detail',
            field=models.TextField(default='fever'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Animal_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease_name', models.CharField(max_length=30)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.animal_category')),
            ],
        ),
        migrations.AlterField(
            model_name='symtoms',
            name='disease_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.animal_disease'),
        ),
    ]
