# Generated by Django 3.2.3 on 2021-05-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210522_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='disease_symtoms',
            new_name='disease_symptoms',
        ),
        migrations.RenameModel(
            old_name='symtoms',
            new_name='symptoms',
        ),
        migrations.RenameField(
            model_name='symptoms',
            old_name='symtom_detail',
            new_name='symptom_detail',
        ),
    ]
