# Generated by Django 3.2.3 on 2021-05-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210522_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease_symptoms',
            name='disease_id',
        ),
        migrations.RemoveField(
            model_name='disease_symptoms',
            name='symptom_id',
        ),
        migrations.RemoveField(
            model_name='doc_specialist_ids',
            name='disease_id',
        ),
        migrations.RemoveField(
            model_name='doc_specialist_ids',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='mydiseases',
            name='vaccine_id',
        ),
        migrations.DeleteModel(
            name='bodypartdisease',
        ),
        migrations.DeleteModel(
            name='disease_symptoms',
        ),
        migrations.DeleteModel(
            name='doc_specialist_ids',
        ),
        migrations.DeleteModel(
            name='mybodyparts',
        ),
        migrations.DeleteModel(
            name='mydiseases',
        ),
    ]
