# Generated by Django 3.2.3 on 2021-05-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210522_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal_category',
            new_name='myAnimal_category',
        ),
        migrations.RenameModel(
            old_name='Animal_Disease',
            new_name='myAnimal_Disease',
        ),
        migrations.RenameModel(
            old_name='symptoms',
            new_name='mysymptoms',
        ),
    ]
