# Generated by Django 3.2.3 on 2021-05-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_mylaws_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylaws',
            name='text',
        ),
    ]
