# Generated by Django 3.2.3 on 2021-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_name_myanimal_disease_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybookappointment',
            name='app_status',
            field=models.CharField(choices=[('A', 'Approved'), ('NA', 'Not Approved'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
