# Generated by Django 3.2.3 on 2021-06-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_mybookappointment_app_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybookappointment',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='mybookappointment',
            name='app_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('NA', 'Not Approved')], default='P', max_length=2),
        ),
    ]
