# Generated by Django 3.2.3 on 2021-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210603_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhospital',
            name='city',
            field=models.CharField(default='amrtisar', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mybookappointment',
            name='app_status',
            field=models.CharField(choices=[('NA', 'Not Approved'), ('P', 'Pending'), ('A', 'Approved')], default='P', max_length=2),
        ),
    ]
